### ISSUE TITLE
Textmining error on Workflow A.9

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#161]
https://arax.ncats.io/?source=ARS&id=1bb22918-c6f3-4aa8-bfcd-b82af2c310ef

EGFR

![image](https://user-images.githubusercontent.com/83781286/125845141-cacea4ac-f159-4e36-9e52-9ac61031d7e4.png)

**Comment by vgardner-renci** [comment]
```
{
  "callback": "http://0.0.0.0:8000/ars/api/messages/8477f662-bdbf-4090-a6f5-2558f9c113fe",
  "max_results": 100,
  "message": {
    "query_graph": {
      "edges": {
        "e0": {
          "object": "n1",
          "predicates": [
            "biolink:negatively_regulates_entity_to_entity",
            "biolink:entity_negatively_regulates_entity"
          ],
          "subject": "n0"
        }
      },
      "nodes": {
        "n0": {
          "categories": [
            "biolink:ChemicalSubstance"
          ],
          "name": "Chemical Substance"
        },
        "n1": {
          "ids": [
            "PR:000006933"
          ],
          "name": "EGFR"
        }
      }
    }
  },
  "validation_result": {
    "message": "",
    "size": "1 kB",
    "status": "PASS",
    "version": "1.1.1"
  }
}

**Comment by bill-baumgartner** [comment]
This `error` would be better classified as a `timeout`.  There was an issue last week with BTE timeouts, and since Text Mining Provider is hosted by Service Provider I think the timeouts affected our service as well. They appear to be resolved at this point. 

**Question: would it be worth having the ARS report timeouts as something different than an error?**

I believe this same comment should also apply to the other Text Mining Provider issues from last week: 

- https://github.com/NCATSTranslator/minihackathons/issues/138
- https://github.com/NCATSTranslator/minihackathons/issues/145
- https://github.com/NCATSTranslator/minihackathons/issues/153
- https://github.com/NCATSTranslator/minihackathons/issues/158

**Comment by tursynay** [comment]
Need to differentiate between different 400 and 500 errors, and timeouts, more text on what type of errors occuring

**Comment by vgardner-renci** [comment]
@bill-baumgartner rerunning the same ARAX a week later yields same result on TextMining.

**Comment by bill-baumgartner** [comment]
@vgardner-renci Is there a PK for the most recent run? Thanks!

**Comment by vgardner-renci** [comment]
I'm using the PK embedded in the ARAX link in the first comment. 1bb22918-c6f3-4aa8-bfcd-b82af2c310ef

**Comment by bill-baumgartner** [comment]
Ok, thanks. I could be wrong but I think there should be a new PK each time a query is run. Also, I think the ARS is down for maintenance today so I'm not sure we can run queries.

**Comment by vgardner-renci** [comment]
Textmining returning results

https://arax.ncats.io/index.html?source=ARS&id=f96dd2dc-4f43-4115-8d35-f826be6f07d6

![image](https://user-images.githubusercontent.com/83781286/127487807-c2d47868-7e1f-4724-abf8-a4c150e2b624.png)
