### ISSUE TITLE
KP CHP has an error and no query is coming in

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#24]
2e3c0352-51e1-4665-a74a-93d5bd101364

**Comment by ehinderer** [comment]
@GregHydeDartmouth Any resolution on this?

**Comment by tursynay** [comment]
@GregHydeDartmouth and @ehinderer , wanted to follow up. Any updates for this issue?

**Comment by GregHydeDartmouth** [comment]
@tursynay the fix is pushed onto our dev server currently. Will be pushed into production by the hackathon time tomorrow (6/17). Sorry for the delays!

**Comment by GregHydeDartmouth** [comment]
Fix should be live.

By the way, it's difficult to tell with the primary key above what the query was because the primary key pertains to the results of improving agent from the last hackathon. Pretty sure this was the query though: 


message = {'message' : 
  {'query_graph' : 
    {
      "edges": {
        "e01": {
          "object": "n0",
          "predicates": [
            "biolink:entity_negatively_regulates_entity"
          ],
          "subject": "n1"
        }
      },
      "nodes": {
        "n0": {
          "categories": [
            "biolink:Gene"
          ],
          "ids": [
            "NCBIGene:23221"
          ]
        },
        "n1": {
          "categories": [
            "biolink:Drug"
          ]
        }
      }
    }
  }
}
I'm partially concerned though because I don't actually see the results from improving agent anymore, so I'm worried I have the wrong query? That or ars-dev changed to ars. Regardless our status message shows the result that I'm expecting: Bad request.Unidentified gene curie: ['NCBIGene:23221'].

![output](https://user-images.githubusercontent.com/60626258/122405653-38aa0f80-cf4e-11eb-85a0-1f9e62207937.PNG)

Please feel free to run on your end!
