### ISSUE TITLE
Filtering and ranking by edge properties

### ISSUE THREAD

**Issue by jh111** [NCATSTranslator/minihackathons#299]
In Demo C queries C1 and C3, we are querying for the predicate has_real_world_evidence_of_association_with.

For the Demo query C1, we would like to filter and sort by the following two edge properties.
  Include: Edge property feature_coefficient, > 0, sort highest to lowest
  Include: Edge property relative_frequency, > 0, sort highest to lowest

For Demo query C3, we would like to filter and sort by one edge property
  Include: Edge property observed_to_expected_frequency > 0, sort highest to lowest

@dkoslicki May we get assistance with the first one? It would be great if it might fit pre-relay.
@rtroper

**Comment by rtroper** [comment]
Just a couple of notes. The predicate `has_real_world_evidence_of_association_with` is actually only used in query C1. For query C3, we use the broad `related_to` predicate, because we want to capture all edges between two CURIE-specified nodes. So far, for query C3, we haven't been overwhelmed by results, so filtering/ranking might not be as crucial on that one. But, for query C1, we could definitely benefit by filtering/ranking. Another note on query C1, we already impose a cutoff (>0.4) on feature_coefficient to ensure that the clinical risk KP gives the most relevant responses.

**Comment by jh111** [comment]
Thank you. I should have said C4.  We can query has_real_world_evidence_of_association_with to see whether a potential treatment is used in patients with a disease. A negative value for relative_frequency might suggest the drug is contraindicated for those patients.

C1 is higher priority at this time for the relay.

**Comment by jh111** [comment]
We will not include this in the demo, as not all ARA's support overlays at this time.

**Comment by dkoslicki** [comment]
@jh111 quick question: do you intend not to run any workflow that has operations that can't be done by each ARA? Currently, the different ARAs (and KPs for that matter) have their "specialties" so the Venn diagram of operations/queries that _every_ component or ARA can respond to is rather small. Is it beneficial to limit the demo to only those queries that each component can respond to?

**Comment by jh111** [comment]
ARAs that can't run an overlay should just run without it. Unfortunately, my understanding is that at this time some ARAs won't run at all when there's an overlay. This is why I removed them from the Dec demos.
