### ISSUE TITLE
Unsecret Agent is not returning results, need the team to look into this and let mini-hack know if that is occurate

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#31]
https://arax.ncats.io/?source=ARS&id=7c8d4771-cbdb-4e71-84bc-33fb65e068cb

**Comment by webyrd** [comment]
Unsecret Agent/mediKanren doesn't currently return answers based on literature co-occurrence or normalized Google distance--we focus more on causal connections, which we have found more useful in practice.  We currently aren't using COHD, which seems to have some useful connections.  So, I'm not surprised that Unsecret Agent isn't returning any results for this query--I think this has to do with a lack of causal connections outside of COHD, rather than an error in our server.

**Comment by vgardner-renci** [comment]
7568140c-d38a-4748-982d-332b0187526f related PK

**Comment by vgardner-renci** [comment]
Based on Will's response it looks like UnSecret is not supposed to return results. Closing issue
