### ISSUE TITLE
Add predicates to ARAX results summary table

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#73]
Ask from Chris B -  it would be nice to add predicates to the results summary table (currently Chris has to write code to get that information out of the results, time consuming process.) 

Create a ticket for Eric to build that into the ARAX UI.

**Comment by tursynay** [comment]
Being tested in DEV, not quite complete yet. Revisit at the next mini-hack

**Comment by dkoslicki** [comment]
Predicates per result appear not really feasible in the result table (due to variable length queries) and are better viewed per result. However, @isbluis has now implemented a provenance feature where the union of all predicates (per component) are displayed along with the underlying knowledge sources/providers/aggregators from where they are derived. Eg. hover your mouse on the new "sources" column on this result: https://arax.ncats.io/test/?source=ARS&id=a91b6205-c88a-434e-acb2-a397f4d8dbda or the "Provenance" tab after you've clicked one of the results. Let us know if this is ok to close

**Comment by tursynay** [comment]
Resolved.
