### ISSUE TITLE
BTE validation Error during mini-hackathon 

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#9]
This query generated an error during mini-hack on May 20, 2021. 
Chunlei, please take a look.

Query:
qg = {
  "nodes": {
    "n0": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "name": "Chemical Substance"
    },
    "n1": {
      "name": "EGFR",
      "ids": ["NCBIGene:1956"]
    }
  },
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1",
      "predicates": [
        "biolink:decreases_abundance_of",
        "biolink:decreases_activity_of",
        "biolink:decreases_expression_of",
        "biolink:decreases_synthesis_of",
        "biolink:increases_degradation_of",
        "biolink:disrupts",
        "biolink:negatively_regulates_entity_to_entity"
      ]
    }
  }
}

Error message:
https://arax.ncats.io/?source=ARS&id=90080f07-808c-47db-a042-21a9ce6f4281

**Comment by tursynay** [comment]
@newgene , I wanted follow up on this issue as we have the mini-hackathon this week and we will be revisiting the queries ran at the last round. Were you able to look into this error? Thanks.

**Comment by newgene** [comment]
@tursynay yes, we have identified the issue and are working on the fix.

**Comment by tursynay** [comment]
@newgene , is there an issue that we can check on that shows the progress on the bug? Thank you.

**Comment by newgene** [comment]
sorry, should have updated here as well. We are tracking this issue here internally:

https://github.com/biothings/BioThings_Explorer_TRAPI/issues/171

and also this related one reported by Chris B:

https://github.com/biothings/BioThings_Explorer_TRAPI/issues/202

The fixes to these reported validation errors have already be deployed at https://api.bte.ncats.io/v1/query now.

We will close these issues (and this one too) after some tests.

**Comment by colleenXu** [comment]
The fixes have been deployed and look to be working. I think this issue can be closed.

**Comment by tursynay** [comment]
That's great. Thank you @colleenXu and @newgene.
